### ISSUE TITLE
Setup bmiadmin (or have that team do so) so that ~bmiadmin/awesim/share directory can be written to by admin users

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#12]
Users in PAS1203 or whatever Maciej et al says.

**Comment by ericfranz** [comment]
Part of this should be to set up `~bmiadmin/awesim/share` to ensure that files and directories created under bmiadmin are owned by the group PAS1203: database and mapping files are 664, app directories are 770.

**Comment by MorganRodgers** [comment]
I think that this is done. Re-open if not.
