### ISSUE TITLE
Warning message about fixing "sensitive directory" permissions to 775 is erroneous

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#19]
The directories for the shiny admin app are (mostly) correctly setup:

```
irb(main):003:0> Pathname.new("/users/PAS1203/bmiadmin/awesim/share").stat.mode.to_s(8)
=> "42775"
irb(main):004:0> Pathname.new("/users/PAS1203/bmiadmin/awesim").stat.mode.to_s(8)
=> "40775"
irb(main):005:0> Pathname.new("/users/PAS1203/bmiadmin").stat.mode.to_s(8)
=> "40775"
```

The bug: chmod 2775 /users/PAS1203/bmiadmin/awesim/share is necessary to ensure that files created under that directory have the correct group. chmod 775 would break that

Also: it is only necessary that the admin users have write permissions on /users/PAS1203/bmiadmin/awesim and /users/PAS1203/bmiadmin (i.e. 755 would be good enough) where-as /users/PAS1203/bmiadmin/awesim/share must be 2775.

**Comment by MorganRodgers** [comment]
Added in #26
