### ISSUE TITLE
In users list, add user "gecos" i.e. full names as well

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#25]
Instead of having the display value of the select options for users just be the username, it would also be the gecos name i.e. "an0047 - Eric Franz" instead of just "an0047".

```ruby
Etc.getgrnam('bmishiny').mem.map { |u| { u => Etc.getpwnam(u).gecos } }
=> [{"bmiadmin"=>"BISR Developers"}, {"mrodgers"=>"Morgan Rodgers"},...
```
* This would be a good feature to add here: https://github.com/OSC/ood_support/issues/5 - then simpler code could be used

_Note: it might end up that even this is not enough, and we want something else (like org?). But we can wait on feedback from BISR for that._

**Comment by MorganRodgers** [comment]
Is there any guarantee that the GECOS field is only ever going to just be full names? It looks as though it is intended to be a dumping ground of additional information about a user: https://en.wikipedia.org/wiki/Gecos_field

**Comment by ericfranz** [comment]
It has been full name at OSC since I've been here.

**Comment by MorganRodgers** [comment]
I just spoke with Trey and he described the GECOS field as being the wild west, but felt that it is going to be better come the switch to the OSCUS system. I'll add this as a final feature to the `facl_fixes`.

**Comment by MorganRodgers** [comment]
Added in #26
