### ISSUE TITLE
Change way we build list of managed datasets

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#27]
Currently managed datasets are assumed to be any file or directory under the managed datasets root:

https://github.com/OSC/shiny_admin/blob/d3e6f053e3000efaa89d14ac31ef8209c04beaa8/app/helpers/mappings_helper.rb#L37-L38

Now with new requirements, these datasets should be any sub-directory under the dataset root that contains an .rds file (or .RDS etc.).

For example, if we have this as our /users/PAS1203/bmiadmin/datasets directory root:

```
datasets/
├── franz_hista_alignment
│   ├── data.csv
│   └── data.rds
├── mrodgers_hista_alignment
│   └── data.csv
└── PZS0714
    ├── foo
    │   ├── bar
    │   │   └── data.rds
    │   └── data.rds
    └── mrodgers_hista_alignment
        ├── data.csv
        └── data.RDS
```

then datasets would be:

```sh
/users/PAS1203/bmiadmin/datasets/franz_hista_alignment

/users/PAS1203/bmiadmin/datasets/PZS0714/mrodgers_hista_alignment
# => notice you need a case insensitive check of the extension RDS or rds etc.

/users/PAS1203/bmiadmin/datasets/PZS0714/foo
# => notice bar is not a dataset because it is contained in foo
```

The easiest solution for this is probably using https://ruby-doc.org/stdlib-2.5.1/libdoc/find/rdoc/Find.html. If a directory contains an `rds` file, you use `Find.prune` to avoid entering the directory in future loop iterations.

**Comment by MorganRodgers** [comment]
Implemented in #28.
