### ISSUE TITLE
Don't rescue Exception

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#3]
https://github.com/OSC/shiny_admin/blob/4d5f852d2823394f7e5e2e52709f8e0b1d00f6df/app/models/mapping.rb#L183-L185 and https://github.com/OSC/shiny_admin/blob/4d5f852d2823394f7e5e2e52709f8e0b1d00f6df/app/models/mapping.rb#L205-L207

Never rescue from Exception, since that is the base class for all exceptions. https://stackoverflow.com/questions/10048173/why-is-it-bad-style-to-rescue-exception-e-in-ruby

Rather, you would typically use StandardError. But in this particular case, don't do either. The https://www.rubydoc.info/github/OSC/ood_support/OodSupport/ACLs/Nfs4ACL#add_facl-class_method states it raises either `OodSupport::InvalidPath` or `OodSupport::BadExitCode` so this should be done instead in instances where `add_facl` is being called

**Comment by MorganRodgers** [comment]
Addressed in https://github.com/OSC/shiny_admin/commit/5770218a97d937ab3cb34fa4c8a316b3ecedc132.

**Comment by ericfranz** [comment]
Missed two places:

https://github.com/OSC/shiny_admin/blob/5770218a97d937ab3cb34fa4c8a316b3ecedc132/app/models/mapping.rb#L37

https://github.com/OSC/shiny_admin/blob/5770218a97d937ab3cb34fa4c8a316b3ecedc132/app/models/mapping.rb#L205

**Comment by MorganRodgers** [comment]
https://github.com/OSC/shiny_admin/commit/a329d89d71d69a44ce145a449272e23d3fa141b8 removes the other two, and `ack --ruby --ignore-dir vendor --ignore-dir tmp 'rescue Exc'` shows no results.
