### ISSUE TITLE
Add ability to edit dataset config file

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#35]
I think that a simple solution for now would be to add an edit button to the right of the dataset path on both the main page and the new mapping page. This would open the files app to that directory. Admins can then select the config file and edit that. Borrowing the icons from the job composer that would be glyphicon-edit and glyphicon-pencil.

```html
<a target="_blank" class="btn btn-primary btn-xs" href="URL_TO_OPEN_DATASET_DIR_IN_FILES_APP"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit files</a>
<a target="_blank" class="btn btn-info btn-xs" href="URL_TO_OPEN_DATASET_CONFIG_IN_FILEEDITOR_APP"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit config</a>
```

![screen 2018-11-19 at 3 42 28 pm](https://user-images.githubusercontent.com/512333/48733936-f7c0b180-ec11-11e8-9a60-ecd103d875dd.png)

![screen 2018-11-19 at 3 43 48 pm](https://user-images.githubusercontent.com/512333/48733939-fa230b80-ec11-11e8-9124-db5f6e1152d5.png)

**Comment by MorganRodgers** [comment]
To make this a bit more explicit you're proposing to add links to OnDemand from the Shiny Admin?
