### ISSUE TITLE
Add in-code model validation to prevent multiple mappings to same user-app pair

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#7]
Because of https://github.com/OSC/ood-dashboard/issues/369 we unfortunately cannot support multiple mappings that share the same user-app pair.

For example, with the current app I can add

![screen 2018-07-20 at 5 09 24 pm](https://user-images.githubusercontent.com/512333/43025424-ae193638-8c3f-11e8-8739-1ac6e0904ce1.png)

Since I can't update the form to let the user choose the dataset, when the app is launched I must choose the first valid mapping I find (well I guess I could also update the app code to reject if multiple mappings were found...).

This is probably easiest: http://guides.rubyonrails.org/active_record_validations.html#custom-methods

After the dashboard issue is fixed we will be able to update the form.yml.erb to support this by displaying a dropdown to choose the dataset the user would like to load.

**Comment by MorganRodgers** [comment]
Would you feel comfortable enforcing this with a unique index? Or do you prefer to do this totally in code to avoid having to change the database?

**Comment by MorganRodgers** [comment]
For the time being I've done this with a count query.
