### ISSUE TITLE
Add sorting to the table using datatables

### ISSUE THREAD

**Issue by ericfranz** [OSC/shiny_admin#8]
The quickest way to add sorting to the mappings is https://github.com/rweng/jquery-datatables-rails#twitter-bootstrap-3-installation after adding `gem 'jquery-datatables-rails', '~> 3.4.0'` to the Gemfile. Though we don't use the normal `application.css` sprockets manifest so instead you'd have to do in `application.css.scss` this: `@import "dataTables/bootstrap/3/jquery.dataTables.bootstrap";`. The defaults for the datatables are probably fine.

Example use in OnDemand is the Job Composer app and Active Jobs. Not sure if the code is ideal or if this particular gem is ideal (there is also Rails Assets and webpack in the future but yeah): https://github.com/OSC/ood-myjobs/search?q=datatables&unscoped_q=datatables and https://github.com/OSC/ood-myjobs/search?q=data-table&unscoped_q=data-table

**Comment by MorganRodgers** [comment]
Funny story, I hadn't stripped out the datatables code, so all I have to add is the `data-tables` class to the table and things just work. Branch `sorting` https://github.com/OSC/shiny_admin/commit/41181b4cccc19a8fd7819b78297da20eadb334b8
